---
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=79]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --follow-imports=skip]
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./scripts/codestyle/clang_format.hook -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|proto)$
        exclude: dlrover/go/brain/vendor
  - repo: local
    hooks:
      - id: cpplint-cpp-source
        name: cpplint
        description: Check C++ code style using cpplint.py.
        entry: bash ./scripts/codestyle/cpplint_precommit.hook
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx)$
        exclude: dlrover/go/brain/vendor
  - repo: https://github.com/dnephin/pre-commit-golang.git
    rev: v0.3.3
    hooks:
      - id: go-fmt
        exclude: dlrover/go/brain/vendor
      - id: go-lint
        exclude: dlrover/go/brain/vendor
      - id: no-go-testing
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.8
    hooks:
      - id: shellcheck
        exclude: dlrover/go/brain/vendor
        files: \.(sh)$
  - repo: local
    hooks:
      - id: copyright_checker
        name: copyright_checker
        entry: python ./scripts/codestyle/copyright.py
        language: system
        files: \.(go|py|sh)$
        # yamllint disable-line rule:line-length
        exclude: (operator/api/v1alpha1/|operator/pkg/common/api/v1/|dlrover/go/brain/vendor)
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
        exclude:
          (elasticdl/python/tests/data|operator/config|dlrover/go/brain/vendor)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint
        name: markdownlint
        description: "Checks the style of Markdown files."
        entry: markdownlint
        language: node
        exclude: (dlrover/go/brain/vendor)
        args: [-s, .markdownlint.yaml]
