---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: scalers.elastic.iml.github.io
spec:
  group: elastic.iml.github.io
  names:
    kind: Scaler
    listKind: ScalerList
    plural: scalers
    singular: scaler
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Scaler is the Schema for the scalers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ScalerSpec defines the desired resource state of an ElasticJob
            properties:
              nodeResourceSpec:
                additionalProperties:
                  description: ResourceSpec specifies the resources of a repalica
                  properties:
                    cpu:
                      description: CPU is the requested CPU cores of a replica
                      type: string
                    gpu:
                      description: GPU is the requested GPU of a replica
                      type: string
                    memory:
                      description: Memory is the requested memory (MB) of a replica
                      type: string
                  type: object
                description: NodeResourceSpec specifics resources configurations of
                  nodes.
                type: object
              ownerJob:
                description: OwnerJob specifies a job to scale.
                type: string
              replicaResourceSpec:
                additionalProperties:
                  description: ReplicaResourceSpec specifies the number and resources
                    of replica.
                  properties:
                    replicas:
                      description: Replicas is the number of replica
                      type: integer
                    resource:
                      description: Resource defines the resource of each replica
                      properties:
                        cpu:
                          description: CPU is the requested CPU cores of a replica
                          type: string
                        gpu:
                          description: GPU is the requested GPU of a replica
                          type: string
                        memory:
                          description: Memory is the requested memory (MB) of a replica
                          type: string
                      type: object
                  type: object
                description: 'A map of ReplicaType (type) to ReplicaSpec (value).
                  Specifies the resource of a job. For example, { "PS": ReplicaResourceSpec,
                  "worker": ReplicaResourceSpec, }'
                type: object
            type: object
          status:
            description: ScalerStatus defines the observed state of ElasticJob
            properties:
              createTime:
                description: CreateTime represents time when the scaler was acknowledged
                  by the scaler controller.
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
