---
repos:
  - repo: https://github.com/asottile-archive/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [--settings-path, atorch/]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--settings-path, atorch/]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        exclude: __init__.py$
        args: [
          "--max-line-length=120", 
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.900
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --follow-imports=skip]
