apiVersion: v1
kind: ConfigMap
metadata:
  name: dlrover-brain-processors
  namespace: dlrover
data:
  processors: |
    running_training_job_optimize_request_processor:
      name: "running_training_job_optimize_request_processor"
