name: build and publish dlrover whl to pypi

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: easydl/dlrover:ci

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

#      - name: Install Build Tools
#        run: |
#          python -m pip install --upgrade pip
#          pip install build twine

      - name: Build Package
        run: sh scripts/build_wheel.sh

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
#        env:
#          TWINE_USERNAME: dlrover
#          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#        run: |
#          python -m twine upload dist/dlrover*
